### ISSUE TITLE
copy edit on instructions

### ISSUE THREAD

**Issue by caike** [codeschool-projects/CodeBreakerProject#15]
![build_a_code_breaker_game_with_javascript___code_school](https://cloud.githubusercontent.com/assets/10722/22252686/05b0e0ea-e21d-11e6-83db-e8c4556de50b.jpg)

How about: if `validateInput` returns `false`, then use `return false` to stop execution...

**Comment by caike** [comment]
![build_a_code_breaker_game_with_javascript___code_school](https://cloud.githubusercontent.com/assets/10722/22252967/f16e038c-e21d-11e6-8b7b-aeb3971ac56e.jpg)

How about: you can negate a value on the `if` statement by using the exclamation point, like this: `if(!someValue)`

**Comment by EricJFisher** [comment]
Changes have been made both to .com tasks and `readme.md` file
