### ISSUE TITLE
Website instructions don't match GitHub instructions

### ISSUE THREAD

**Issue by Moocow89** [codeschool-projects/CodeBreakerProject#17]
Instructions on the website (https://www.codeschool.com/projects/build-a-code-breaker-game-with-javascript/build) do not match the instructions on the GitHub README.md (particularly Step 11 and Step 12). The website instructions are wrong and need to be replaced with the repo instructions.

**Comment by EricJFisher** [comment]
I've corrected tasks 11 and 12 on the website (I'll also make a minor adjustment to twelve in the repo) I'll also make a pass through all the instructions again to make sure everything matches up. Thank you for pointing this out to us!
