### ISSUE TITLE
Markdown doesn't render in task names

### ISSUE THREAD

**Issue by jonfriskics** [codeschool-projects/CodeBreakerProject#4]
<img width="740" alt="build_a_code_breaker_game_with_javascript___code_school" src="https://cloud.githubusercontent.com/assets/381284/22216935/0aa04388-e16f-11e6-9467-3b00e9cf477d.png">

**Comment by jonfriskics** [comment]
lol, that's "remove backticks".  Get any backpacks out of there too.

**Comment by jonfriskics** [comment]
To be clear - my recommendation is to just remove any markdown from task names, not to add support for it.

**Comment by EricJFisher** [comment]
Removed all backticks from task names on the .com, removed `"'` combos from both .com and `readme.md` (in the `readme.md` these were replaced with backticks since github does proper markdown)
