### ISSUE TITLE
First Task Instructions unclear

### ISSUE THREAD

**Issue by jonfriskics** [codeschool-projects/CodeBreakerProject#5]
For the "Create setHiddenFields Function" the instructions are:

```
Our application uses the answer hidden input to store the answer to the game. Our setHiddenFields method should not use any parameters, but needs to set the awnser hidden input to a randomly generated number between 0 and 9999.
```

This doesn't specifically say anything about what a student is supposed to do for this step.  I recommend something like this:

```
Create a function named `setHiddenFields` that sets the `answer` variable equal to a randomly generated number between 0 and 9999.
```

**Comment by jonfriskics** [comment]
Also, Hint 1 can be cleaned up too.

`Math.round()` can be used to randomly generate a number between 0 and 1 (up to 18 decimal points) and Math.floor(input), Math.ceiling(input), or Math.round(input) can be used to then round that number either up or down.

**Comment by jonfriskics** [comment]
Not sure what the point of Hint 2 is here - we don't have to call `getElementById` in this task, right?

**Comment by jonfriskics** [comment]
Also in Hint 1 - says "Math.round() can be used to randomly generate...", it's actually Math.random(), right?

**Comment by EricJFisher** [comment]
I've updated the details on task 1 in both the .com and `readme.md` for clarity.
