### ISSUE TITLE
Task 8 issue

### ISSUE THREAD

**Issue by jonfriskics** [codeschool-projects/CodeBreakerProject#7]
In the task "Only set the "answer" and "attempt" hidden inputs when they aren't already set", it starts with:

"When we go to call the `setHiddenFields` functions in our `guess` function, we should only update our hidden inputs when they're not set."

Should that instead be something like:

"Call the `setHiddenFields()` function in the body of the `guess()` function, but also write some logic so that it's only called when `answer` and `attempt` haven't already been set."

**Comment by EricJFisher** [comment]
Updated in both the .com and `readme.md` file.
